c/ed/plain: visual stub
Textual user interface can be enabled by running ./build +visual as an
optional feature.

diff --git a/c/ed/build b/c/ed/build
--- a/c/ed/build
+++ b/c/ed/build
@@ -2,7 +2,24 @@
 # Simple script that creates a Makefile for all c files that contain a main function
 CC=gcc
 cstd='-std=gnu99'
-CFLAGS="-Wall -Wextra -pedantic $cstd $*"
+libs=
+for i in "$@"; do
+	case "$i" in
+	+visual)
+		shift 1
+		libs='ncurses'
+		CFLAGS="$CFLAGS -DVISUAL"
+		if ! hash pkg-config 2>/dev/null; then
+			echo "pkg-config is missing" 1>&2
+			exit 1
+		fi
+		;;
+	--)
+		shift 1
+		break;;
+	esac
+done
+CFLAGS="$CFLAGS -Wall -Wextra -pedantic $cstd $*"
 INCS=
 cat <<END >.gitignore
 # Created by build script. Modifications are lost when rerun.
@@ -16,12 +33,18 @@ Makefile
 *.o
 END
 CFLAGS="$CFLAGS $INCS"
+LDLIBS=
+if [ ! -z "$libs" ]; then
+	CFLAGS="$CFLAGS $(pkg-config --cflags $libs)"
+	LDLIBS="$(pkg-config --libs $libs)"
+fi
 # Write phony target and overwrite some builtin variables
 cat <<END >Makefile
 .PHONY: default clean
 
 CC?=$CC
 CFLAGS=$CFLAGS
+LDLIBS=$LDLIBS
 
 END
 
